#!/bin/sh -eu

. $(dirname $0)/../core/runner

testname="init-drop-deps"

banner "${testname}"
#----------

INPUT_DIR=$(dirname $0)/data
OUTPUT_DIR=${TEST}
EXPECTED_DIR=$(dirname $0)/expected

mkdir -p ${OUTPUT_DIR}

cp -f ${INPUT_DIR}/* ${OUTPUT_DIR}/

(cd ${OUTPUT_DIR} && \
  git init && \
  git add stack.yaml ${testname}.cabal && \
  git commit -m "Initial commit" -- . && \
  ${JENGA} init --drop-deps directory,filepath )

assert_file_exists ${OUTPUT_DIR}/${testname}.lock-8.0.2
assert_file_exists ${OUTPUT_DIR}/.jenga

error=0
compare_files ${OUTPUT_DIR}/${testname}.lock-8.0.2 ${EXPECTED_DIR}/${testname}.lock-8.0.2
compare_files ${OUTPUT_DIR}/.jenga ${EXPECTED_DIR}/jenga.yaml

if test "${error}" = "0"; then
	pass_test
else
	fail_test
fi
