#!/bin/sh -eu

. $(dirname $0)/../core/runner

testname="update"

banner "${testname}"
#----------

INPUT_DIR=$(dirname $0)/data
OUTPUT_DIR=${TEST}
EXPECTED_DIR=$(dirname $0)/expected

mkdir -p ${OUTPUT_DIR}

cp -f ${INPUT_DIR}/* ${OUTPUT_DIR}/
rm -f ${OUTPUT_DIR}/stack*.yaml
cp -f ${INPUT_DIR}/stack-7.0.yaml ${OUTPUT_DIR}/stack.yaml

(cd ${OUTPUT_DIR} && \
  git init && \
  git add stack.yaml ${testname}.cabal && \
  git commit -m "Initial commit" -- . && \
  ${JENGA} init )

error=0
assert_file_exists ${OUTPUT_DIR}/${testname}.lock-8.0.1
assert_file_exists ${OUTPUT_DIR}/lib/stm/stm.cabal
assert_file_exists ${OUTPUT_DIR}/lib/wide-word/wide-word.cabal
assert_file_exists ${OUTPUT_DIR}/.jenga

compare_files ${OUTPUT_DIR}/${testname}.lock-8.0.1 ${EXPECTED_DIR}/${testname}.lock-8.0.1
compare_files ${OUTPUT_DIR}/.jenga ${EXPECTED_DIR}/jenga-7.0.yaml

(cd ${OUTPUT_DIR} && \
  git commit -m "Add submodules" -- . && \
  ${JENGA} init )

# Update the stack version.
cp -f ${INPUT_DIR}/stack-9.1.yaml ${OUTPUT_DIR}/stack.yaml

(cd ${OUTPUT_DIR} && \
  ${JENGA} update  && \
  git commit -m "Update stack resolver and wide-word, remove stm" -- . )

assert_file_exists ${OUTPUT_DIR}/lib/wide-word/wide-word.cabal
assert_file_absent ${OUTPUT_DIR}/lib/stm/stm.cabal
assert_file_exists ${OUTPUT_DIR}/${testname}.lock-8.0.2
assert_file_exists ${OUTPUT_DIR}/.jenga

compare_files ${OUTPUT_DIR}/${testname}.lock-8.0.2 ${EXPECTED_DIR}/${testname}.lock-8.0.2
compare_files ${OUTPUT_DIR}/.jenga ${EXPECTED_DIR}/jenga-9.1.yaml

if test "${error}" = "0"; then
	pass_test
else
	fail_test
fi
