#!/bin/sh -eu

. $(dirname $0)/../core/runner

testname="genlock"

banner "${testname}"
#----------

INPUT_DIR=$(dirname $0)/data
OUTPUT_DIR=${TEST}
EXPECTED_DIR=$(dirname $0)/expected

mkdir -p $(dirname ${OUTPUT_DIR})

cp -f ${INPUT_DIR}/* ${OUTPUT_DIR}

$JENGA genlock --cabal ${OUTPUT_DIR}/first.cabal --stack ${OUTPUT_DIR}/stack.yaml 2>/dev/null

assert_file_exists ${OUTPUT_DIR}/first.lock-8.0.2

error=0
diff -q ${OUTPUT_DIR}/first.lock-8.0.2 ${EXPECTED_DIR}/first.lock-8.0.2 || error=1

if test "${error}" = "0"; then
    echo "PASSED [ ${testname} ]"
    echo
else
    echo ""
    echo "FAILED [ ${testname} ]"
    echo ""
    mgdiff ${OUTPUT_DIR}/first.lock-8.0.2 ${EXPECTED_DIR}/first.lock-8.0.2
    exit_cleanup
fi
